repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace 
    -   id: check-executables-have-shebangs # best practice
    -   id: check-json # verifies json syntax
    -   id: check-yaml # verifies yaml syntax check-symlinks
    -   id: check-symlinks # empty symlinks detector
    -   id: destroyed-symlinks # broken symlinks detector
    -   id: detect-aws-credentials # detects AWS credentials & does not allow commit to be made NOTE: if ~/.aws folder is not in the default installed location, set env vars: AWS_CONFIG_FILE or AWS_CREDENTIAL_FILE
